// Code generated by the Encore 1.49.3 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly analytics: analytics.ServiceClient
    public readonly blockchain: blockchain.ServiceClient
    public readonly events: events.ServiceClient
    public readonly nft: nft.ServiceClient
    public readonly token: token.ServiceClient
    public readonly transaction: transaction.ServiceClient
    public readonly wallet: wallet.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.analytics = new analytics.ServiceClient(base)
        this.blockchain = new blockchain.ServiceClient(base)
        this.events = new events.ServiceClient(base)
        this.nft = new nft.ServiceClient(base)
        this.token = new token.ServiceClient(base)
        this.transaction = new transaction.ServiceClient(base)
        this.wallet = new wallet.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getDailyStats as api_analytics_analytics_getDailyStats,
    getHealthMetrics as api_analytics_analytics_getHealthMetrics,
    getNetworkActivity as api_analytics_analytics_getNetworkActivity,
    getOverview as api_analytics_analytics_getOverview,
    getTokenAnalytics as api_analytics_analytics_getTokenAnalytics,
    getTopHolders as api_analytics_analytics_getTopHolders
} from "~backend/analytics/analytics";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDailyStats = this.getDailyStats.bind(this)
            this.getHealthMetrics = this.getHealthMetrics.bind(this)
            this.getNetworkActivity = this.getNetworkActivity.bind(this)
            this.getOverview = this.getOverview.bind(this)
            this.getTokenAnalytics = this.getTokenAnalytics.bind(this)
            this.getTopHolders = this.getTopHolders.bind(this)
        }

        /**
         * Get daily statistics for the last 30 days
         */
        public async getDailyStats(params: RequestType<typeof api_analytics_analytics_getDailyStats>): Promise<ResponseType<typeof api_analytics_analytics_getDailyStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                days: params.days === undefined ? undefined : String(params.days),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/daily`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_analytics_getDailyStats>
        }

        /**
         * Get blockchain health metrics
         */
        public async getHealthMetrics(): Promise<ResponseType<typeof api_analytics_analytics_getHealthMetrics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_analytics_getHealthMetrics>
        }

        /**
         * Get network activity statistics
         */
        public async getNetworkActivity(): Promise<ResponseType<typeof api_analytics_analytics_getNetworkActivity>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/networks`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_analytics_getNetworkActivity>
        }

        /**
         * Get blockchain overview dashboard
         */
        public async getOverview(): Promise<ResponseType<typeof api_analytics_analytics_getOverview>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/overview`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_analytics_getOverview>
        }

        /**
         * Get token analytics
         */
        public async getTokenAnalytics(): Promise<ResponseType<typeof api_analytics_analytics_getTokenAnalytics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/tokens`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_analytics_getTokenAnalytics>
        }

        /**
         * Get top token holders for a specific token
         */
        public async getTopHolders(params: RequestType<typeof api_analytics_analytics_getTopHolders>): Promise<ResponseType<typeof api_analytics_analytics_getTopHolders>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/tokens/${encodeURIComponent(params.tokenId)}/holders`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_analytics_getTopHolders>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createNetwork as api_blockchain_networks_createNetwork,
    getNetwork as api_blockchain_networks_getNetwork,
    listNetworks as api_blockchain_networks_listNetworks,
    toggleNetworkStatus as api_blockchain_networks_toggleNetworkStatus
} from "~backend/blockchain/networks";
import {
    createContract as api_blockchain_smart_contracts_createContract,
    deleteContract as api_blockchain_smart_contracts_deleteContract,
    getContract as api_blockchain_smart_contracts_getContract,
    listContracts as api_blockchain_smart_contracts_listContracts,
    updateContract as api_blockchain_smart_contracts_updateContract
} from "~backend/blockchain/smart_contracts";

export namespace blockchain {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createContract = this.createContract.bind(this)
            this.createNetwork = this.createNetwork.bind(this)
            this.deleteContract = this.deleteContract.bind(this)
            this.getContract = this.getContract.bind(this)
            this.getNetwork = this.getNetwork.bind(this)
            this.listContracts = this.listContracts.bind(this)
            this.listNetworks = this.listNetworks.bind(this)
            this.toggleNetworkStatus = this.toggleNetworkStatus.bind(this)
            this.updateContract = this.updateContract.bind(this)
        }

        /**
         * Create a new smart contract
         */
        public async createContract(params: RequestType<typeof api_blockchain_smart_contracts_createContract>): Promise<ResponseType<typeof api_blockchain_smart_contracts_createContract>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/contracts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_smart_contracts_createContract>
        }

        /**
         * Create a new blockchain network
         */
        public async createNetwork(params: RequestType<typeof api_blockchain_networks_createNetwork>): Promise<ResponseType<typeof api_blockchain_networks_createNetwork>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/networks`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_networks_createNetwork>
        }

        /**
         * Delete a smart contract
         */
        public async deleteContract(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/blockchain/contracts/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Get a specific smart contract by ID
         */
        public async getContract(params: { id: number }): Promise<ResponseType<typeof api_blockchain_smart_contracts_getContract>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/contracts/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_smart_contracts_getContract>
        }

        /**
         * Get a specific network by ID
         */
        public async getNetwork(params: { id: number }): Promise<ResponseType<typeof api_blockchain_networks_getNetwork>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/networks/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_networks_getNetwork>
        }

        /**
         * List all smart contracts
         */
        public async listContracts(): Promise<ResponseType<typeof api_blockchain_smart_contracts_listContracts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/contracts`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_smart_contracts_listContracts>
        }

        /**
         * List all blockchain networks
         */
        public async listNetworks(): Promise<ResponseType<typeof api_blockchain_networks_listNetworks>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/networks`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_networks_listNetworks>
        }

        /**
         * Toggle network active status
         */
        public async toggleNetworkStatus(params: { id: number }): Promise<ResponseType<typeof api_blockchain_networks_toggleNetworkStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/networks/${encodeURIComponent(params.id)}/toggle`, {method: "PATCH", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_networks_toggleNetworkStatus>
        }

        /**
         * Update an existing smart contract
         */
        public async updateContract(params: RequestType<typeof api_blockchain_smart_contracts_updateContract>): Promise<ResponseType<typeof api_blockchain_smart_contracts_updateContract>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                abi:        params.abi,
                isVerified: params.isVerified,
                name:       params.name,
                version:    params.version,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blockchain/contracts/${encodeURIComponent(params.id)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blockchain_smart_contracts_updateContract>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createEvent as api_events_events_createEvent,
    eventStream as api_events_events_eventStream,
    getEvent as api_events_events_getEvent,
    getEventsByContract as api_events_events_getEventsByContract,
    getEventsByTransaction as api_events_events_getEventsByTransaction,
    listEvents as api_events_events_listEvents,
    simulateEvent as api_events_events_simulateEvent
} from "~backend/events/events";

export namespace events {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createEvent = this.createEvent.bind(this)
            this.eventStream = this.eventStream.bind(this)
            this.getEvent = this.getEvent.bind(this)
            this.getEventsByContract = this.getEventsByContract.bind(this)
            this.getEventsByTransaction = this.getEventsByTransaction.bind(this)
            this.listEvents = this.listEvents.bind(this)
            this.simulateEvent = this.simulateEvent.bind(this)
        }

        /**
         * Create a new blockchain event
         */
        public async createEvent(params: RequestType<typeof api_events_events_createEvent>): Promise<ResponseType<typeof api_events_events_createEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/events`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_events_createEvent>
        }

        /**
         * Real-time event streaming endpoint
         */
        public async eventStream(params: RequestType<typeof api_events_events_eventStream>): Promise<StreamIn<StreamResponse<typeof api_events_events_eventStream>>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                contractAddress: params.contractAddress,
                eventName:       params.eventName,
                networkId:       params.networkId === undefined ? undefined : String(params.networkId),
            })

            return await this.baseClient.createStreamIn(`/events/stream`, {query})
        }

        /**
         * Get specific event by ID
         */
        public async getEvent(params: { id: number }): Promise<ResponseType<typeof api_events_events_getEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/events/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_events_getEvent>
        }

        /**
         * Get events by contract address
         */
        public async getEventsByContract(params: RequestType<typeof api_events_events_getEventsByContract>): Promise<ResponseType<typeof api_events_events_getEventsByContract>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                eventName: params.eventName,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                page:      params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/contract/${encodeURIComponent(params.contractAddress)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_events_getEventsByContract>
        }

        /**
         * Get events by transaction hash
         */
        public async getEventsByTransaction(params: { transactionHash: string }): Promise<ResponseType<typeof api_events_events_getEventsByTransaction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/transaction/${encodeURIComponent(params.transactionHash)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_events_getEventsByTransaction>
        }

        /**
         * List blockchain events with filtering
         */
        public async listEvents(params: RequestType<typeof api_events_events_listEvents>): Promise<ResponseType<typeof api_events_events_listEvents>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                blockNumber:     params.blockNumber === undefined ? undefined : String(params.blockNumber),
                contractAddress: params.contractAddress,
                eventName:       params.eventName,
                limit:           params.limit === undefined ? undefined : String(params.limit),
                networkId:       params.networkId === undefined ? undefined : String(params.networkId),
                page:            params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/events`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_events_listEvents>
        }

        /**
         * Simulate blockchain events (for testing purposes)
         */
        public async simulateEvent(params: RequestType<typeof api_events_events_simulateEvent>): Promise<ResponseType<typeof api_events_events_simulateEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/simulate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_events_simulateEvent>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    buyNFT as api_nft_nft_buyNFT,
    cancelListing as api_nft_nft_cancelListing,
    createListing as api_nft_nft_createListing,
    createNFT as api_nft_nft_createNFT,
    getNFT as api_nft_nft_getNFT,
    getNFTsByOwner as api_nft_nft_getNFTsByOwner,
    listMarketplace as api_nft_nft_listMarketplace,
    listNFTs as api_nft_nft_listNFTs
} from "~backend/nft/nft";

export namespace nft {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.buyNFT = this.buyNFT.bind(this)
            this.cancelListing = this.cancelListing.bind(this)
            this.createListing = this.createListing.bind(this)
            this.createNFT = this.createNFT.bind(this)
            this.getNFT = this.getNFT.bind(this)
            this.getNFTsByOwner = this.getNFTsByOwner.bind(this)
            this.listMarketplace = this.listMarketplace.bind(this)
            this.listNFTs = this.listNFTs.bind(this)
        }

        /**
         * Buy NFT from marketplace
         */
        public async buyNFT(params: RequestType<typeof api_nft_nft_buyNFT>): Promise<ResponseType<typeof api_nft_nft_buyNFT>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/marketplace/buy`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_buyNFT>
        }

        /**
         * Cancel marketplace listing
         */
        public async cancelListing(params: RequestType<typeof api_nft_nft_cancelListing>): Promise<ResponseType<typeof api_nft_nft_cancelListing>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/marketplace/cancel`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_cancelListing>
        }

        /**
         * Create marketplace listing
         */
        public async createListing(params: RequestType<typeof api_nft_nft_createListing>): Promise<ResponseType<typeof api_nft_nft_createListing>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/marketplace/list`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_createListing>
        }

        /**
         * Create/Mint NFT
         */
        public async createNFT(params: RequestType<typeof api_nft_nft_createNFT>): Promise<ResponseType<typeof api_nft_nft_createNFT>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/nfts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_createNFT>
        }

        /**
         * Get specific NFT
         */
        public async getNFT(params: { id: number }): Promise<ResponseType<typeof api_nft_nft_getNFT>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/nfts/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_getNFT>
        }

        /**
         * Get NFTs by owner
         */
        public async getNFTsByOwner(params: { ownerAddress: string }): Promise<ResponseType<typeof api_nft_nft_getNFTsByOwner>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/owner/${encodeURIComponent(params.ownerAddress)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_getNFTsByOwner>
        }

        /**
         * List marketplace items
         */
        public async listMarketplace(): Promise<ResponseType<typeof api_nft_nft_listMarketplace>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/marketplace`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_listMarketplace>
        }

        /**
         * List all NFTs
         */
        public async listNFTs(): Promise<ResponseType<typeof api_nft_nft_listNFTs>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nft/nfts`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nft_nft_listNFTs>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    burnToken as api_token_token_burnToken,
    createToken as api_token_token_createToken,
    getToken as api_token_token_getToken,
    listTokens as api_token_token_listTokens,
    mintToken as api_token_token_mintToken,
    transferToken as api_token_token_transferToken
} from "~backend/token/token";

export namespace token {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.burnToken = this.burnToken.bind(this)
            this.createToken = this.createToken.bind(this)
            this.getToken = this.getToken.bind(this)
            this.listTokens = this.listTokens.bind(this)
            this.mintToken = this.mintToken.bind(this)
            this.transferToken = this.transferToken.bind(this)
        }

        /**
         * Burn tokens (simulated)
         */
        public async burnToken(params: RequestType<typeof api_token_token_burnToken>): Promise<ResponseType<typeof api_token_token_burnToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/token/burn`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_token_token_burnToken>
        }

        /**
         * Create a new token
         */
        public async createToken(params: RequestType<typeof api_token_token_createToken>): Promise<ResponseType<typeof api_token_token_createToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/token/tokens`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_token_token_createToken>
        }

        /**
         * Get a specific token by ID
         */
        public async getToken(params: { id: number }): Promise<ResponseType<typeof api_token_token_getToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/token/tokens/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_token_token_getToken>
        }

        /**
         * List all tokens
         */
        public async listTokens(): Promise<ResponseType<typeof api_token_token_listTokens>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/token/tokens`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_token_token_listTokens>
        }

        /**
         * Mint tokens (simulated - in real implementation this would interact with blockchain)
         */
        public async mintToken(params: RequestType<typeof api_token_token_mintToken>): Promise<ResponseType<typeof api_token_token_mintToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/token/mint`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_token_token_mintToken>
        }

        /**
         * Transfer tokens (simulated)
         */
        public async transferToken(params: RequestType<typeof api_token_token_transferToken>): Promise<ResponseType<typeof api_token_token_transferToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/token/transfer`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_token_token_transferToken>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createTransaction as api_transaction_transaction_createTransaction,
    getTransaction as api_transaction_transaction_getTransaction,
    getTransactionStats as api_transaction_transaction_getTransactionStats,
    getTransactionsByAddress as api_transaction_transaction_getTransactionsByAddress,
    listTransactions as api_transaction_transaction_listTransactions,
    updateTransaction as api_transaction_transaction_updateTransaction
} from "~backend/transaction/transaction";

export namespace transaction {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createTransaction = this.createTransaction.bind(this)
            this.getTransaction = this.getTransaction.bind(this)
            this.getTransactionStats = this.getTransactionStats.bind(this)
            this.getTransactionsByAddress = this.getTransactionsByAddress.bind(this)
            this.listTransactions = this.listTransactions.bind(this)
            this.updateTransaction = this.updateTransaction.bind(this)
        }

        /**
         * Create a new transaction record
         */
        public async createTransaction(params: RequestType<typeof api_transaction_transaction_createTransaction>): Promise<ResponseType<typeof api_transaction_transaction_createTransaction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/transaction/transactions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_transaction_transaction_createTransaction>
        }

        /**
         * Get specific transaction by hash
         */
        public async getTransaction(params: { hash: string }): Promise<ResponseType<typeof api_transaction_transaction_getTransaction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/transaction/${encodeURIComponent(params.hash)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_transaction_transaction_getTransaction>
        }

        /**
         * Get transaction statistics
         */
        public async getTransactionStats(params: RequestType<typeof api_transaction_transaction_getTransactionStats>): Promise<ResponseType<typeof api_transaction_transaction_getTransactionStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                networkId: params.networkId === undefined ? undefined : String(params.networkId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/transaction/stats`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_transaction_transaction_getTransactionStats>
        }

        /**
         * Get transactions by address (for wallet transaction history)
         */
        public async getTransactionsByAddress(params: RequestType<typeof api_transaction_transaction_getTransactionsByAddress>): Promise<ResponseType<typeof api_transaction_transaction_getTransactionsByAddress>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/transaction/address/${encodeURIComponent(params.address)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_transaction_transaction_getTransactionsByAddress>
        }

        /**
         * List transactions with pagination and filters
         */
        public async listTransactions(params: RequestType<typeof api_transaction_transaction_listTransactions>): Promise<ResponseType<typeof api_transaction_transaction_listTransactions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                address:   params.address,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                networkId: params.networkId === undefined ? undefined : String(params.networkId),
                page:      params.page === undefined ? undefined : String(params.page),
                status:    params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/transaction/transactions`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_transaction_transaction_listTransactions>
        }

        /**
         * Update transaction status (when confirmed on blockchain)
         */
        public async updateTransaction(params: RequestType<typeof api_transaction_transaction_updateTransaction>): Promise<ResponseType<typeof api_transaction_transaction_updateTransaction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/transaction/update`, {method: "PATCH", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_transaction_transaction_updateTransaction>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createWallet as api_wallet_wallet_createWallet,
    getWallet as api_wallet_wallet_getWallet,
    getWalletBalance as api_wallet_wallet_getWalletBalance,
    listWallets as api_wallet_wallet_listWallets,
    updateWalletLastUsed as api_wallet_wallet_updateWalletLastUsed
} from "~backend/wallet/wallet";

export namespace wallet {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createWallet = this.createWallet.bind(this)
            this.getWallet = this.getWallet.bind(this)
            this.getWalletBalance = this.getWalletBalance.bind(this)
            this.listWallets = this.listWallets.bind(this)
            this.updateWalletLastUsed = this.updateWalletLastUsed.bind(this)
        }

        /**
         * Create a new wallet
         */
        public async createWallet(params: RequestType<typeof api_wallet_wallet_createWallet>): Promise<ResponseType<typeof api_wallet_wallet_createWallet>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wallet/wallets`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wallet_wallet_createWallet>
        }

        /**
         * Get a specific wallet by address
         */
        public async getWallet(params: { address: string }): Promise<ResponseType<typeof api_wallet_wallet_getWallet>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wallet/${encodeURIComponent(params.address)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wallet_wallet_getWallet>
        }

        /**
         * Get wallet balances (tokens)
         */
        public async getWalletBalance(params: { address: string }): Promise<ResponseType<typeof api_wallet_wallet_getWalletBalance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wallet/${encodeURIComponent(params.address)}/balance`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wallet_wallet_getWalletBalance>
        }

        /**
         * List all wallets for a user
         */
        public async listWallets(params: RequestType<typeof api_wallet_wallet_listWallets>): Promise<ResponseType<typeof api_wallet_wallet_listWallets>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wallet/wallets`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wallet_wallet_listWallets>
        }

        /**
         * Update wallet last used timestamp
         */
        public async updateWalletLastUsed(params: { address: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/wallet/${encodeURIComponent(params.address)}/update-usage`, {method: "PATCH", body: undefined})
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.49.3)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
